In [ ]:
import numpy as np  

# 1
arr = np.ones((3, 3), dtype=bool)
print(arr)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [3]:
#2
arr_ID = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr_2D = arr_ID.reshape(3, 3)
print("arr_2D ban đầu:")
print(arr_2D)

# Đổi cột 1 và cột 3 (index 0 và 2)
arr_2D[:, [0, 2]] = arr_2D[:, [2, 0]]
print("arr_2D sau khi đổi cột 1 và 3:")
print(arr_2D)


arr_2D ban đầu:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
arr_2D sau khi đổi cột 1 và 3:
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [4]:
#3
arr_2D[[0, 1]] = arr_2D[[1, 0]]
print("Sau khi đổi dòng 1 và 2:")
print(arr_2D)


Sau khi đổi dòng 1 và 2:
[[5 4 3]
 [2 1 0]
 [8 7 6]]


In [5]:
#4
arr_2D = arr_2D[::-1]
print("Sau khi đảo ngược các dòng:")
print(arr_2D)


Sau khi đảo ngược các dòng:
[[8 7 6]
 [2 1 0]
 [5 4 3]]


In [6]:
#5
arr_2D = arr_2D[:, ::-1]
print("Sau khi đảo ngược các cột:")
print(arr_2D)


Sau khi đảo ngược các cột:
[[6 7 8]
 [0 1 2]
 [3 4 5]]


In [8]:
#6
arr_2D_null = np.array([
    [1, 2, 3],
    [np.nan, 5, 6],
    [7, np.nan, 9],
    [4, 5, 6]
])

print(arr_2D_null)

# Kiểm tra NaN
has_nan = np.isnan(arr_2D_null).any()
print("Array có chứa giá trị NaN không:", has_nan)


[[ 1.  2.  3.]
 [nan  5.  6.]
 [ 7. nan  9.]
 [ 4.  5.  6.]]
Array có chứa giá trị NaN không: True


In [9]:
#7
arr_2D_null = np.nan_to_num(arr_2D_null, nan=0)
print("Sau khi thay NaN bằng 0:")
print(arr_2D_null)


Sau khi thay NaN bằng 0:
[[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]
